# Generated by Django 5.0.2 on 2024-02-22 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_about_created_at_alter_about_describe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technology',
            name='label',
        ),
    ]
