# Generated by Django 5.0.2 on 2024-02-22 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_remove_technology_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='label',
        ),
    ]
