# Generated by Django 5.0.2 on 2024-02-15 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('thumbnail', models.ImageField(upload_to='blog_thumbnail')),
                ('slug', models.SlugField(default='')),
                ('description', models.TextField(blank=True, null=True)),
                ('posted_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
