# Generated by Django 5.0.2 on 2024-02-19 15:32

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='Text'),
        ),
    ]
